### ISSUE TITLE
Need clear information about joint states 

### ISSUE THREAD

**Issue by ekorudiawan** [ROBOTIS-GIT/ROBOTIS-Framework#85]
I use Darwin OP3 robot which uses XM430-W350 Dynamixel servo. I want to read current data in Ampere using ROBOTIS-Framework. 
As I know, I can subscribe present joint states in topic 

`
/robotis/present_joint_states
`

This topic publishes position, velocity, and effort. Is the effort contains value of joint torque? Because the servo motor doesn't have torque sensor, or it is just approximation?

In devices folder, there is XM430-W350.device that lists all information of the motor. I found a scaling factor

`
torque_to_current_value_ratio   = 149.795386991
`

Where this value comes from?
How can I convert effort value in joint states to current (in Ampere)?

**Comment by onjinwook** [comment]
Hi, I'm Jin.

if you want to read the effort, you need to do something.
  1) check this link -> [OP3.robot](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3/blob/master/op3_manager/config/OP3.robot)
    : you may find and add "BULK READ ITEMS" -> [prensent_current](https://github.com/ROBOTIS-GIT/ROBOTIS-Framework/blob/288e048adeb5195dae49626d044a30190fbab46c/robotis_device/devices/dynamixel/XM430-W350.device#L73)

After that you make use of "torque_to_current_value_ratio" in framework.
*ps : The" torque_to_current_value_ratio value" is an actual measurement and may not be accurate.

Regards,
Jin.

**Comment by ekorudiawan** [comment]
```
check this link -> OP3.robot
: you may find and add "BULK READ ITEMS" -> prensent_current
```
I am done with this, here an example reading
```
---
header: 
  seq: 880
  stamp: 
    secs: 25
    nsecs: 196000000
  frame_id: ''
name: - head_pan
- head_tilt
- l_ank_pitch
- l_ank_roll
- l_el
- l_hip_pitch
- l_hip_roll
- l_hip_yaw
- l_knee
- l_sho_pitch
- l_sho_roll
- r_ank_pitch
- r_ank_roll
- r_el
- r_hip_pitch
- r_hip_roll
- r_hip_yaw
- r_knee
- r_sho_pitch
- r_sho_roll
position: [8.420455125346393e-05, -0.0036501271747759745, -0.5074470885658897, -0.021233422276620395, -0.0005806854408909601, -0.9877315103525266, 0.02190427963862085, 0.006478857119786241, 1.2347772174846146, -0.2624526561998568, 1.3985380369619849, -0.505774797156783, 0.024472363280158227, 0.0006823349379478927, -0.9868821049928496, -0.021583271204584698, -0.007204199157222924, 1.2324199986224231, 0.2625453673115734, 1.3992656564533164]
velocity: [0.012730165317048889, 0.006602381264101093, 0.031290642219176754, -0.1671884450877372, 0.0012968547747411532, 0.012262565514619156, 0.03416588217015005, 0.0027814892795186043, 0.08419838527850326, 0.014732007522410162, -0.009373388961215968, 0.06461045145225715, 0.12410907878294766, 0.0014696812823669601, 0.028675257190019912, -0.009886637881570931, -0.00015261822575412913, 0.05049065780656754, -0.0047445688506732725, 0.010304926419331981]
effort: [-0.0003574316151899737, 0.01828303354011407, 0.27393444414847146, -0.23760928455174302, 0.005819751340796486, 0.265826754705234, 0.1535365403074973, 0.009660529969401921, -0.601800504936767, 0.007786059116590138, -0.022840644861021886, 0.19194477979218583, 0.07354303810855889, -0.00680874408325316, 0.22416885356322247, -0.16837590038334405, 0.026744237372655633, -0.4855997182856786, -0.008613453302279694, -0.02991980491987789]

```
My question, what is unit in effort value? 
Is it an approximation of torque in Nm? Or it represents an "electric current" in Ampere?
If it is just approximation of torque value, how to scale this value to get actual "electric current"?

Actually, I want to read "electric current" data not "torque" data
